package executionenvironment

import (
	"shared/shared"
	"os"
	"verificationtools/fdr"
	"framework/configuration/configuration"
	"framework/message"
	"graph/execgraph"
	"strings"
	"shared/errors"
	"framework/configuration/commands"
	"strconv"
	"shared/parameters"
	"executionenvironment/adaptationmanager"
	"executionenvironment/versioninginjector"
	"executionenvironment/executionunit"
	"framework/libraries"
	"framework/element"
)

type ExecutionEnvironment struct{}

func (ee ExecutionEnvironment) Deploy(adlFileName string) {

	// Load execution parameters
	shared.LoadParameters(os.Args[1:])

	// Perform checks on library
	libraries.CheckLibrary()

	// Generate Go configuration
	conf := configuration.MapADLIntoGo(adlFileName)

	// Configure management/structural channels and maps
	managementChannels := ConfigureManagementChannels(conf)
	ee.ConfigureStructuralChannelsAndMaps(&conf)

	// Check behaviour using FDR
	fdrChecker := new(fdr.FDR)
	ok := fdrChecker.CheckBehaviour(conf)
	if !ok {
		myError := errors.MyError{Source: "Execution Engine", Message: "Configuration has a problem detected by FDR4"}
		myError.ERROR()
	}

	// Generate *.dot files
	// FDR.GenerateFDRGraphs()

	// Load graph generated by FDR (*.dot)
	fdrChecker.LoadFDRGraphs(&conf)

	// Generate executable graph
	CreateExecGraphs(&conf)

	// Show execution parameters
	shared.ShowExecutionParameters(false)

	// Start adaptation manager
	if parameters.IS_CORRECTIVE || parameters.IS_EVOLUTIVE || parameters.IS_PROACTIVE {
		go adaptationmanager.AdaptationManager{}.Exec(conf, managementChannels)
		go versioninginjector.InjectAdaptiveEvolution(parameters.PLUGIN_BASE_NAME)
	}

	// Start execution units
	for c := range conf.Components {
		go executionunit.ExecutionUnit{}.Exec(conf.Components[c], managementChannels[conf.Components[c].Id])
	}

	for t := range conf.Connectors {
		go executionunit.ExecutionUnit{}.Exec(conf.Connectors[t], managementChannels[conf.Connectors[t].Id])
	}
}

func ConfigureManagementChannels(conf configuration.Configuration) map[string]chan commands.LowLevelCommand {
	managementChannels := make(map[string]chan commands.LowLevelCommand)
	for i := range conf.Components {
		id := conf.Components[i].Id
		managementChannels[id] = make(chan commands.LowLevelCommand)
	}
	return managementChannels
}

func CreateExecGraphs(conf *configuration.Configuration) {

	// Components
	for c := range conf.Components {
		graph := execgraph.NewGraph(conf.Components[c].FDRGraph.NumNodes)
		eActions := execgraph.Action{}
		var msg message.Message
		for e1 := range conf.Components[c].FDRGraph.Edges {
			for e2 := range conf.Components[c].FDRGraph.Edges[e1] {
				edgeTemp := conf.Components[c].FDRGraph.Edges[e1][e2]
				actionNameFDR := edgeTemp.Action
				actionNameExec := ""
				if strings.Contains(actionNameFDR, ".") {
					actionNameExec = actionNameFDR[:strings.Index(actionNameFDR, ".")]
				}
				if shared.IsExternal(actionNameExec) { // External action
					key := conf.Components[c].Id + "." + actionNameFDR
					channel := conf.StructuralChannels[key]
					params := execgraph.Action{}
					switch actionNameExec {
					case "InvR":
						invr := channel
						params = execgraph.Action{ExternalAction: element.Element{}.InvR, Message: &msg, ActionChannel: &invr, ActionName: actionNameExec}
					case "TerR":
						terr := channel
						params = execgraph.Action{ExternalAction: element.Element{}.TerR, Message: &msg, ActionChannel: &terr, ActionName: actionNameExec}
					case "InvP":
						invp := channel
						params = execgraph.Action{ExternalAction: element.Element{}.InvP, Message: &msg, ActionChannel: &invp, ActionName: actionNameExec}
					case "TerP":
						terp := channel
						params = execgraph.Action{ExternalAction: element.Element{}.TerP, Message: &msg, ActionChannel: &terp, ActionName: actionNameExec}
					}
					mapType := execgraph.Action{}
					mapType = params
					eActions = mapType
				}

				if shared.IsInternal(actionNameFDR) {
					msg := message.Message{}
					params := execgraph.Action{InternalAction: shared.Invoke, ActionName: actionNameFDR, Message: &msg}
					mapType := params
					eActions = mapType
				}
				graph.AddEdge(edgeTemp.From, edgeTemp.To, eActions)
			}
		}
		tempComp := conf.Components[c]
		tempComp.SetExecGraph(graph)
		conf.Components[c] = tempComp
	}

	// Connectors
	for t := range conf.Connectors {
		graph := execgraph.NewGraph(conf.Connectors[t].FDRGraph.NumNodes)
		eActions := execgraph.Action{}
		var msg message.Message
		for e1 := range conf.Connectors[t].FDRGraph.Edges {
			for e2 := range conf.Connectors[t].FDRGraph.Edges[e1] {
				edgeTemp := conf.Connectors[t].FDRGraph.Edges[e1][e2]
				actionNameFDR := edgeTemp.Action
				actionNameExec := ""
				if strings.Contains(actionNameFDR, ".") {
					actionNameExec = actionNameFDR[:strings.Index(actionNameFDR, ".")]
				}
				if shared.IsExternal(actionNameExec) { // External action
					key := conf.Connectors[t].Id + "." + actionNameFDR
					channel := conf.StructuralChannels[key]
					params := execgraph.Action{}
					switch actionNameExec {
					case "InvR":
						invr := channel
						params = execgraph.Action{ExternalAction: element.Element{}.InvR, Message: &msg, ActionChannel: &invr, ActionName: actionNameExec}
					case "TerR":
						terr := channel
						params = execgraph.Action{ExternalAction: element.Element{}.TerR, Message: &msg, ActionChannel: &terr, ActionName: actionNameExec}
					case "InvP":
						invp := channel
						params = execgraph.Action{ExternalAction: element.Element{}.InvP, Message: &msg, ActionChannel: &invp, ActionName: actionNameExec}
					case "TerP":
						terp := channel
						params = execgraph.Action{ExternalAction: element.Element{}.TerP, Message: &msg, ActionChannel: &terp, ActionName: actionNameExec}
					}
					mapType := execgraph.Action{}
					mapType = params
					eActions = mapType
				}

				if shared.IsInternal(actionNameFDR) {
					msg := message.Message{}
					params := execgraph.Action{InternalAction: shared.Invoke, ActionName: actionNameFDR, Message: &msg}
					mapType := params
					eActions = mapType
				}
				graph.AddEdge(edgeTemp.From, edgeTemp.To, eActions)
			}
		}
		tempComp := conf.Connectors[t]
		tempComp.SetExecGraph(graph)
		conf.Connectors[t] = tempComp
	}
}

func (ExecutionEnvironment) ConfigureStructuralChannelsAndMaps(conf *configuration.Configuration) {
	structuralChannels := make(map[string]chan message.Message)

	// Configure structural channels
	for i := range conf.Attachments {
		c1Id := conf.Attachments[i].C1.Id
		c2Id := conf.Attachments[i].C2.Id
		tId := conf.Attachments[i].T.Id

		// c1 -> t
		key01 := c1Id + "." + shared.INVR + "." + tId
		key02 := tId + "." + shared.INVP + "." + c1Id
		key03 := tId + "." + shared.TERP + "." + c1Id
		key04 := c1Id + "." + shared.TERR + "." + tId
		structuralChannels[key01] = make(chan message.Message, parameters.CHAN_BUFFER_SIZE)
		structuralChannels[key02] = structuralChannels[key01]
		structuralChannels[key03] = make(chan message.Message, parameters.CHAN_BUFFER_SIZE)
		structuralChannels[key04] = structuralChannels[key03]

		// t -> c2
		key01 = tId + "." + shared.INVR + "." + c2Id
		key02 = c2Id + "." + shared.INVP + "." + tId
		key03 = c2Id + "." + shared.TERP + "." + tId
		key04 = tId + "." + shared.TERR + "." + c2Id
		structuralChannels[key01] = make(chan message.Message, parameters.CHAN_BUFFER_SIZE)
		structuralChannels[key02] = structuralChannels[key01]
		structuralChannels[key03] = make(chan message.Message, parameters.CHAN_BUFFER_SIZE)
		structuralChannels[key04] = structuralChannels[key03]
	}
	conf.StructuralChannels = structuralChannels

	// Configure maps
	elemMaps := make(map[string]string)
	partners := make(map[string]string)

	for i := range conf.Attachments {
		c1Id := conf.Attachments[i].C1.Id
		c2Id := conf.Attachments[i].C2.Id
		tId := conf.Attachments[i].T.Id
		if !strings.Contains(partners[c1Id], tId) {
			partners[c1Id] += ":" + tId
		}
		if !strings.Contains(partners[tId], c1Id) {
			partners[tId] += ":" + c1Id
		}
		if !strings.Contains(partners[tId], c2Id) {
			partners[tId] += ":" + c2Id
		}
		if !strings.Contains(partners[c2Id], tId) {
			partners[c2Id] += ":" + tId
		}
	}

	for i := range partners {
		p := strings.Split(partners[i], ":")
		c := 1
		for j := range p {
			if p[j] != "" {
				elemMaps[i+".e"+strconv.Itoa(c)] = p[j]
				c++
			}
		}
	}
	conf.Maps = elemMaps
}
